baseURL = 'https://example.org/'
languageCode = 'fr-FR'
defaultContentLanguage = "fr"
title = 'Geoffrey'
theme = 'ananke'


[params]
read_more_copy = "Read more about this entry"
body_classes = "yellow"
background_color_class = "yellow"
text_color = "green"
